# Generated by Django 5.0.6 on 2024-05-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("bank_name", models.CharField(max_length=255)),
            ],
        ),
    ]
