# Generated by Django 5.0.6 on 2024-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
